/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:2.3.0.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-jdbc:2.3.0.RELEASE")
    implementation("org.projectlombok:lombok:1.18.12")
    runtimeOnly("org.postgresql:postgresql:42.2.12")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.3.0.RELEASE")
}

group = "org.github"
version = "0.0.1-SNAPSHOT"
description = "joker"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
